### ISSUE TITLE
Cannot be used with pyinstaller

### ISSUE THREAD

**Issue by timrprobocom** [richardpenman/whois#104]
When a project that uses `whois` is converted to an executable, the resulting exe fails because the `data/public_suffix_list.dat` file cannot be found.

I have two suggestions: either add something to the "readme" telling folks how to add that file to the directives file, or just convert that file to a Python module and include it in the source instead of the data file.

**Comment by richardpenman** [comment]
if you have details how to get pyinstaller working feel free to open a Pull Request adding these details to the README

**Comment by selltool** [comment]
Me too :((((
