### ISSUE TITLE
Can't parse dates on .rs domains

### ISSUE THREAD

**Issue by mongolito12345** [richardpenman/whois#106]
sample code:
```
import whois
domain = whois.whois("domain.rs")
print(domain.creation_date)
```

The above code will print 'None', even though the dates are visible in the whois.

Sample of whois response:
```
Registration date: 01.08.2020 13:11:08
Modification date: 13.09.2021 10:05:55
Expiration date: 01.08.2022 17:19:38
```

I did fix it locally by addinbg a class WhoisRS to use the proper regex, but would be nice to implement in future update

**Comment by freedom45678** [comment]
can share your code about WhoisRS ?
