### ISSUE TITLE
AttributeError: module 'whois' has no attribute 'whois'

### ISSUE THREAD

**Issue by jarh1992** [richardpenman/whois#108]
I installed python-whois on win11 using pip, after import it and call it on interactive console I got this error:
`>>> import whois`
`>>> w = whois.whois('webscraping.com')`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`AttributeError: module 'whois' has no attribute 'whois'`

Doing a pip freeze I have:
`python-whois==0.7.3`

**Comment by jarh1992** [comment]
with python-whois==0.7.2, the previous sentences works

**Comment by natanzi** [comment]
Dears,
this issue is exist....
ERROR Python Script        3:4        Execute failed: module 'whois' has no attribute 'query'
Traceback (most recent call last):
  File "<string>", line 9, in <module>
AttributeError: module 'whois' has no attribute 'query'

**Comment by logicsys** [comment]
Please ensure you are using the python-whois pip package rather than the whois pip package which is a different project entirely

**Comment by jarh1992** [comment]
From my side I'm sure I was using python-whois. Looking again, the error has apparently disappeared.
