### ISSUE TITLE
.ai domains are failing

### ISSUE THREAD

**Issue by vivekhub** [richardpenman/whois#110]
`In [13]: whois('whois.ai')

Out[13]: 
{'domain_name': None,
 'name': None,
 'org': None,
 'address': None,
 'city': 'The Valley',
 'state': None,
 'zipcode': None,
 'country': 'AI',
 'name_servers': None}`

**Comment by richardpenman** [comment]
Pull request welcome to fix the WhoisAI parser

**Comment by vivekhub** [comment]
Sent a pull request
