### ISSUE TITLE
Checking unregistered domain return fatal error

### ISSUE THREAD

**Issue by DNS** [richardpenman/whois#112]
Checking unregistered domain return fatal error.

**Code:**
```
import whois
w = whois.whois('test0276409.com')
```

**Output:**
```
Traceback (most recent call last):
  File "E:\SANDBOX\domain-expiration-monitor-py.py", line 7, in <module>
    w = whois.whois('test0276409.com')
```

Expected result should only return output something like _"No whois information found"_ rather than fatal error.

**Comment by richardpenman** [comment]
this is an exception, which is the standard way to handle way to handle errors in python
