### ISSUE TITLE
Date parsing is wrong for some domains (registrars?)

### ISSUE THREAD

**Issue by tzeppy** [richardpenman/whois#116]
whois.whois("tierramor.cr")

{'domain_name': 'tierramor.cr', 'registrant': 'CON-13656', 'registrar': 'NIC-REG1', 'updated_date': [datetime.datetime(2022, 1, 2, 6, 36, 45), datetime.datetime(2022, 1, 2, 6, 36, 44)], 'creation_date': datetime.datetime(2022, 4, 1, 9, 26, 15), 'expiration_date': datetime.datetime(2023, 4, 1, 0, 0), 'name_servers': ['ns1.siteground.net', 'ns2.siteground.net'], 'status': None, 'contact': 'CON-13656', 'name': 'Matthew Richards', 'org': 'TIERRAMOR LIMITADA', 'address': ['Correo Nosara', 'Box 60', 'NOSARA', '50206', 'Guanacaste', 'CR'], 'phone': '+1.8312521445'}

creation-date should be Jan 4th, not April 1st, etc.

**Comment by mindlesstux** [comment]
What gets me is some have double dates for updated_date (your example) and/or creation_date and/or expiration_date.  What I have seen is usually a GMT/UTC0 + Local to the registrar.  It would be nice if I knew which one was the GMT/UTC0.

**Comment by richardpenman** [comment]
Closing as no reply
