### ISSUE TITLE
Creation/Updated Dates

### ISSUE THREAD

**Issue by elsheikh21** [richardpenman/whois#121]
Hello

I am using your package to fetch domain last updated date and creation date, for some analysis
I just want to make sure that the dates used are related for the domain itself. not to the DNS server or Authorative server

```python
import whois


ip_address = "8.8.8.8"
whois_obj = whois.whois(ip_address)
creation_date = whois_obj.get('creation_date')
updated_date = whois_obj.get('updated_date')
print(creation_date, updated_date, sep='\n')
```

**Comment by richardpenman** [comment]
sorry what's the question here?

**Comment by richardpenman** [comment]
Closing since inactive
