### ISSUE TITLE
AttributeError: partially initialized module 'whois' has no attribute 'query'

### ISSUE THREAD

**Issue by StalKlim** [richardpenman/whois#122]
I found a little piece of code for an example:
```
import whois
w = whois.query('google.com')
w.name_servers
```

And after launching it I get the following error:
```
Traceback (most recent call last):
  File "c:/Users/stalv/Desktop/whois.py", line 1, in <module>
    import whois
  File "c:\Users\stalv\Desktop\whois.py", line 2, in <module>
    w = whois.query('google.com')
AttributeError: partially initialized module 'whois' has no attribute 'query' (most likely due to a circular import)
```

Python version 3.8.8, library version 0.7.3
There are no libraries in the system other than this one (I specially for the test completely reinstalled Python, because I tried another library before)
![image](https://user-images.githubusercontent.com/16457247/167521265-c90b6c8a-d032-443f-ab5f-1bc63262f7d4.png)

**Comment by richardpenman** [comment]
not sure where you got that example from, but it is wrong. Try the example in the README:
https://github.com/richardpenman/whois#example
