### ISSUE TITLE
AttributeError: module 'whois' has no attribute 'whois'

### ISSUE THREAD

**Issue by ALEXDINO7** [richardpenman/whois#141]
import whois

w = whois.whois('mywebsitehere.com')
print(w.expiration_date)

I get this error

AttributeError: module 'whois' has no attribute 'whois'

**Comment by HenryObj** [comment]
Hi
Check that the package installed is "python-whois==0.8.0".
You might have another package "whois" installed.
You can see this with the command "pip freeze > requirements.txt" then opening the requirements.txt file and checking if you have the right / multiple "whois" installed.
Then relaunch everything and it should work.
