### ISSUE TITLE
enhancement proposal: add unparsed response to the result dict as new key

### ISSUE THREAD

**Issue by gremur** [richardpenman/whois#150]
Due to possible problems with data parsing and, as a result, the possibility of losing part of the data, I suggest to include raw data to the resulting dictionary in a separate key like the following:

```
{
"domain_name": "...",
"registrar": "...",
"creation_date": "...",
....
"whois": raw whois data
}
```

**Comment by richardpenman** [comment]
That's a great idea. I was going to implement this and then realized it's already supported with the `inc_raw` argument:
https://github.com/richardpenman/whois/blob/master/whois/__init__.py#L53
