### ISSUE TITLE
why some domain's organization field is registrant_organization and other is registrant_org or org

### ISSUE THREAD

**Issue by ev01ing** [richardpenman/whois#152]
in com entry is org field
in cl is registrant_organization
in jp is registrant_org

![image](https://user-images.githubusercontent.com/12087409/206100662-5cae15a6-01eb-4cb7-95d8-080bbd2ec9a8.png)
![image](https://user-images.githubusercontent.com/12087409/206100693-b16db8ef-777d-46a2-9905-e0b8e52ec074.png)
![image](https://user-images.githubusercontent.com/12087409/206100766-a0cb7f06-43c4-435e-a84e-d74d0d4dfb99.png)

**Comment by ev01ing** [comment]
why not use one specific field like registrant_organization in all tld domain?

**Comment by richardpenman** [comment]
that is a good idea - PR welcome to standardize this field

**Comment by richardpenman** [comment]
Closing as no one seems motivated to standardize this field
