### ISSUE TITLE
wowkorea.jp parse error

### ISSUE THREAD

**Issue by ev01ing** [richardpenman/whois#153]
```
import whois
w = whois.whois("wowkorea.jp")
w
```
output is:
```
{'domain_name': 'WOWKOREA.JP',
 'registrant_org': 'AISE,Inc',
 'creation_date': None,
 'expiration_date': None,
 'name_servers': ['ns1.whois.ne.jp',
  'ns2.whois.ne.jp',
  'ns1.whoisweb.jp',
  'ns2.whoisweb.jp'],
 'updated_date': None,
 'status': None}
```

but the text is :
```
print(w.text)
```
```
[ JPRS database provides information on network administration. Its use is    ]
[ restricted to network administration purposes. For further information,     ]
[ use 'whois -h whois.jprs.jp help'. To suppress Japanese output, add'/e'     ]
[ at the end of command, e.g. 'whois -h whois.jprs.jp xxx/e'.                 ]

Domain Information: [ドメイン情報]
[Domain Name]                   MAINICHI.JP

[登録者名]                      株式会社 毎日新聞社
[Registrant]                    THE MAINICHI NEWSPAPERS

[Name Server]                   ns-1113.awsdns-11.org
[Name Server]                   ns-449.awsdns-56.com
[Name Server]                   ns-763.awsdns-31.net
[Name Server]                   ns-1828.awsdns-36.co.uk
[Signing Key]                   

[登録年月日]                    2001/03/26
[有効期限]                      2023/03/31
[状態]                          Active
[最終更新]                      2022/04/01 01:05:09 (JST)

Contact Information: [公開連絡窓口]
[名前]                          株式会社 毎日新聞社
[Name]                          THE MAINICHI NEWSPAPERS
[Email]                         m-soumu@mainichi.co.jp
[Web Page]                       
[郵便番号]                      100-8051
[住所]                          東京都千代田区一ツ橋1-1-1
[Postal Address]                1-1-1 Hitotsubashi
                                Chiyoda-ku
[電話番号]                      03-3212-0220
[FAX番号]                       03-3287-1320
```

**Comment by ev01ing** [comment]
get another answer in English
    [ JPRS database provides information on network administration. Its use is    ]
    [ restricted to network administration purposes. For further information,     ]
    [ use 'whois -h whois.jprs.jp help'. To suppress Japanese output, add'/e'     ]
    [ at the end of command, e.g. 'whois -h whois.jprs.jp xxx/e'.                 ]
    
    Domain Information:
    [Domain Name]                   WOWKOREA.JP
    
    [Registrant]                    AISE,Inc
    
    [Name Server]                   ns1.whois.ne.jp
    [Name Server]                   ns2.whois.ne.jp
    [Name Server]                   ns1.whoisweb.jp
    [Name Server]                   ns2.whoisweb.jp
    [Signing Key]
    
    [Created on]                    2006/08/22
    [Expires on]                    2023/08/31
    [Status]                        Active
    [Last Updated]                  2022/09/01 01:05:08 (JST)
    
    Contact Information:
    [Name]                          WHOIS co, ltd.
    [Email]                         whois@whois.ne.jp
    [Web Page]
    [Postal code]                   160-0004
    [Postal Address]                4-13-17 Yotuya,Shinjyuku-ku,Tokyo
    [Phone]                         03-5379-1705
    [Fax]                           03-5379-1709

**Comment by richardpenman** [comment]
PR would be welcome to fix the jp TLD

**Comment by mzpqnxow** [comment]
> PR would be welcome to fix the jp TLD

What are your thoughts on supporting both the native language for WHOIS servers _and_ English? Perhaps via an argument in the high level interface that could easily be exposed to the example (or any other) cli?

There are prefixes or suffixes for some of the WHOIS servers to specify which language you want, on some it's something like "/e" - you may already be familiar with and support this, I don't recall

I do recall actually having special handling for JP in specific in the ugly fork I have, to reliably and fully parse JP domains, because some either have only a Japanese language record, or have only partial data in English (or Japanese)

I intended to send this upstream and either forgot/got busy, or it required invasive changes

Either way, I'll look into it if I can..,

**Comment by mzpqnxow** [comment]
Derp, it's right there in the output:

>  To suppress Japanese output, add'/e'     ]
> [ at the end of command, e.g. 'whois -h whois.jprs.jp xxx/

This would explain any discrepancy in output of native whois vs this package

That, plus the parsing is a little different depending on language, I think?

**Comment by mzpqnxow** [comment]
For reference, here is the current JP parser class:

    class WhoisJp(WhoisEntry):
        """Whois parser for .jp domains"""

        regex = {
            "domain_name": r".*\[Domain Name\]\s*(.+)",
            "registrant_org": r".*\[(?:Organization|Registrant)\](.+)",
            "creation_date": r"\[(?:Registered Date|Created on|登録年月日)\]\s*(.+)",
            "expiration_date": r"\[(?:Expires on|有効期限)\]\s*(.+)",
            "name_servers": r".*\[Name Server\]\s*(.+)",  # list of name servers
            "updated_date": r"\[(?:Last Updated|最終更新)?\]\s?(.+)",
        "".status": r"\[(?:State|Status|状態)\]\s*(.+)",  # list of statuses
    }

        def __init__(self, domain, text):
            if "No match!!" in text:
                raise PywhoisError(text)
            else:
                WhoisEntry.__init__(self, domain, text, self.regex)

**Comment by mzpqnxow** [comment]
I submitted #225 for this, but I encourage you to review the changes. I made a modification to `whois.py` that you may not desire as default behavior

**Comment by mzpqnxow** [comment]
@ev01ing this should be fixed and can be closed
