### ISSUE TITLE
Raise exceptions instead of log it

### ISSUE THREAD

**Issue by gilbd** [richardpenman/whois#155]
Hi, I think it will be super cool if a user can send a flag signal to the package it used as a 3rd party package, and leave the exception handling to the user.

For example:
https://github.com/richardpenman/whois/blob/a8ec0e789f99d1e21d384641eba2750aeb9be766/whois/whois.py#L212

Here just raise it..

**Comment by richardpenman** [comment]
excellent point - PR would be welcome
