### ISSUE TITLE
.co returns Error trying to connect to socket: closing socket

### ISSUE THREAD

**Issue by mkishi1221** [richardpenman/whois#168]
Searching for .co domains returns error: Error trying to connect to socket: closing socket

```
>>> print(w)

Error trying to connect to socket: closing socket
{
  "domain_name": null,
  "registrar": null,
  "whois_server": null,
  "referral_url": null,
  "updated_date": null,
  "creation_date": null,
  "expiration_date": null,
  "name_servers": null,
  "status": null,
  "emails": null,
  "dnssec": null,
  "name": null,
  "org": null,
  "address": null,
  "city": null,
  "state": null,
  "zipcode": null,
  "country": null
}

```

**Comment by soumboussaha** [comment]
I have the same issue where you able to solve it ?

**Comment by mkishi1221** [comment]
I haven't found a fix for it yet.

**Comment by soumboussaha** [comment]
in my case it happens for all request I see you mention it happens for you for specifically domains ending with :  .co , is that right ?

**Comment by mkishi1221** [comment]
Yes that's correct! I haven't had that problem with other TLDs.

**Comment by mir-technologies** [comment]
Hi guys, any resolution? In have the same issue

**Comment by richardpenman** [comment]
If you are getting this error for all domains then is likely a network problem

**Comment by richardpenman** [comment]
Closing as no follow-up and likely a network problem
