### ISSUE TITLE
Make postal code and state/province consistent

### ISSUE THREAD

**Issue by RensOliemans** [richardpenman/whois#17]
There are two fields which are used inconsistently but where it isn't trivial to choose.

## Postal Code
The two fields used are:
`registrant_postal_code`, for example in `WhoisClub`, and
`zipcode`, for example in `WhoisInfo`.

I think that the `.info zipcode` field should be `registrant_zipcode` but that is a change for later.
For this issue, should we make `postal_code` the standard? It seems to be the field most used for this purpose.

## State/Province
The field used are:
`registrant_state_province`, f.e. `WhoisBiz`, and
`state`, f.e. `WhoisInfo`.

Again, `.info state` should prob. be `registrant_state`, but that isn't the point of this issue.
What field should be the standard?

**Comment by richardpenman** [comment]
yeah definitely needs to be more consistent. I would prefer postal_code over zip_code because is more commonly used internationally.
