### ISSUE TITLE
Default timeout

### ISSUE THREAD

**Issue by gilbd** [richardpenman/whois#174]
Hi, could it be possible to pass a timeout argument instead of hard-coded it to 10?

https://github.com/richardpenman/whois/blob/d2984dfeab630f7f02b0830487e8786f34f7ce6d/whois/whois.py#L178

**Comment by richardpenman** [comment]
Definitely, you're right that shouldn't be hardcoded. I would gladly accept a PR for this.

**Comment by anton-yurchenko** [comment]
Is this released? (https://pypi.org/project/python-whois/#history)
