### ISSUE TITLE
Some registrars have timezones for expiration, some don't

### ISSUE THREAD

**Issue by BillWeissABK** [richardpenman/whois#183]
That big ol' list of regexes at https://github.com/richardpenman/whois/blob/master/whois/parser.py#L34-L75 sometimes gets a timezone and sometimes doesn't. I've got some code that's checking if a domain expires within 30 days and I was doing something like this:
```python
today_plus_30 = datetime.now() + timedelta(days=30)
w = whois.whois(some_domain)
if w['expiration_date'] < today_plus_30:
  print("Ohno")
```

That blows up if the whois lookup has a timezone attached. I end up having to do this:
```python
today_plus_30 = datetime.now(timezone.utc) + timedelta(days=30)
w = whois.whois(some_domain)
expiration = w['expiration_date'].replace(tzinfo=pytz.UTC)
if expiration < today_plus_30:
  print("Ohno")
```

It feels like everyone using this library who is looking at expirations will have to do something similar.

Any thoughts about how to fix? I'm happy to write some code to clean it up :) My first thought is to always add a timezone of UTC if there isn't one included in the expiration date, but that'll mean everyone using the library needs to change their code. We could also strip the tz but that feels like a bummer.

**Comment by richardpenman** [comment]
Stripping all timezones sounds terrible! Might some people find it more useful to know when the timezone is unknown, rather than setting a default of UTC? I haven't worked with expirations so am not sure what would be ideal for this case.

**Comment by BillWeissABK** [comment]
I agree, it's not the preferred solution :) I just want something where I can ask 'is this domain expiring soon' :) I don't know if there's an implicit timezone when one isn't provided, but UTC feels like a safe default to me.

**Comment by richardpenman** [comment]
oh now I understand the problem:

```
>>> from datetime import datetime
>>> d1 = datetime.fromisoformat('2024-03-01T00:00:00')
>>> d2 = datetime.fromisoformat('2024-03-01T00:00:00Z')
>>> now = datetime.now()
>>> now - d1
datetime.timedelta(days=21, seconds=76423, microseconds=389686)
>>> now - d2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't subtract offset-naive and offset-aware datetimes
```

So by default datetime objects are not timezone aware. Sure let's do UTC by default - did you want to submit a PR?

**Comment by BillWeissABK** [comment]
Yeah, you bet. I just wanted to make sure this was a welcome change :)

**Comment by BillWeissABK** [comment]
Thanks!
