### ISSUE TITLE
New DK whois

### ISSUE THREAD

**Issue by povlhp** [richardpenman/whois#185]
DK_HOST = "whois.dk-hostmaster.dk"  should be changed to 'whois.punktum.dk'
DK Hostmaster recently changed name to .DK aka punktum-dk
They are in the process of changing infrastructure. IANA returns this in refer:

$ whois -I plec.dk
% IANA WHOIS server
% for more information on IANA, visit http://www.iana.org
% This query returned 1 object

refer:        whois.punktum.dk

domain:       DK

**Comment by richardpenman** [comment]
PR welcome!

**Comment by richardpenman** [comment]
Closing as no reply
