### ISSUE TITLE
No module named imp

### ISSUE THREAD

**Issue by nmlz** [richardpenman/whois#188]
Hi!
When trying to import whois I get the error mentioned on the title
Probably it could get fixed by whois using importlib instead of imp?

**Comment by PierreAnken** [comment]
Quick fix for me: edit future\standard_library\__init__.py 
`import imp` to `import importlib as imp`

**Comment by nmlz** [comment]
Fixed!

Thank you @PierreAnken!

**Comment by liquidsec** [comment]
Can we reopen this so it gets a proper fix instead of a hacky manual one? I've got a project that uses this library as a dependency. It's already making it broken in python 3.12, and it will be a headache for me until it's fixed.
