### ISSUE TITLE
proposal name swap

### ISSUE THREAD

**Issue by mboot-github** [richardpenman/whois#199]
i am the new owner of the github:python-whois, pypi:whois
you are the owner of github:whois, pypi:python-whois

as you may have noticed, 
we have frequent mix ups between the use of the pypi module and creating issues in the wrong github repo.

i propose we rename the github repos to match the pypi name

the successor of the current github:python-whois, pypi:whois is: 

- github:WhoisDomain, pypi:whoisdomain,

your input is appreciated,

Maarten

**Comment by richardpenman** [comment]
ha, that's funny!
But this module is accessed with `import whois` and I don't want to change that.

**Comment by mboot-github** [comment]
Well I have in the meantime deprecated the pypi whois (GitHub python-whois)
module and moved all activity over to the new whoisdomain.

Maarten

**Comment by richardpenman** [comment]
Could I get the pypi:whois account? I don't want to change the import, which would impact existing usage. But I would be happy to make the pypi account consistent.

**Comment by richardpenman** [comment]
Thanks so much! Will move repo there soon
