### ISSUE TITLE
add domain status

### ISSUE THREAD

**Issue by md-rifatkhan** [richardpenman/whois#202]
can you add domain status for purchase : available or not

**Comment by adamcysec** [comment]
If a domain does not have a whois record, then it is available for purchase. Adding this as a feature may be a bit redundant.

**Comment by md-rifatkhan** [comment]
Yeah you are right but invalid domain also return null

**Comment by richardpenman** [comment]
Do you have an example of a whois record that indicates the domain is for purchase?

**Comment by richardpenman** [comment]
Closing as no example to work from
