### ISSUE TITLE
Missing python-dateutil dependency in package installs

### ISSUE THREAD

**Issue by dspruell** [richardpenman/whois#206]
Python 3.10.12:

Using _whois_ as a project dependency, recently ran into error after an upgrade.

```
Traceback (most recent call last):
    from whois import whois  # type: ignore
  File "/home/dspruell/.local/pipx/venvs/resolve-hosts/lib/python3.10/site-packages/whois/__init__.py", line 8, in <module>
    from .parser import WhoisEntry
  File "/home/dspruell/.local/pipx/venvs/resolve-hosts/lib/python3.10/site-packages/whois/parser.py", line 12, in <module>
    import dateutil.parser as dp
ModuleNotFoundError: No module named 'dateutil'
```
Looks like a required module:

https://github.com/richardpenman/whois/blob/47bc6ec5d37d33dac4eb4cb8049c765db8e4078e/whois/parser.py#L12

...but not currently a dependency in setup.py, it's only in the requirements.txt (not processed by standard dependency resolution in Pip). Should requirements.txt just be migrated to setuptools `install_requires`?

https://github.com/richardpenman/whois/blob/47bc6ec5d37d33dac4eb4cb8049c765db8e4078e/setup.py#L30

**Comment by richardpenman** [comment]
thanks for reporting - could you send a PR to fix this? If not, I'll get to this in a few days.

**Comment by richardpenman** [comment]
Fixed in https://github.com/richardpenman/whois/commit/7422ce7051e52b28683b868307f0235573ba847a
