### ISSUE TITLE
Distinguish between not found and other errors

### ISSUE THREAD

**Issue by infosec-it-init** [richardpenman/whois#21]
As an enhancement it would be nice if certain error cases are distinguished, for example if a domain is not found it gives another Error than when the rate limit exceeded.
Now it just raises a generic PywhoisError

**Comment by pnmartinez** [comment]
That would be a great, great enhancement @richardpenman.
Being able to store "not found" values as variables could add lots of value, e.g. to check for many domains in a loop without raising an error.

**Comment by richardpenman** [comment]
that is a good idea - patch welcome

**Comment by pnmartinez** [comment]
> 
> 
> that is a good idea - patch welcome
Now the library is able to perform WHOIS on loops without stopping on errors (https://github.com/richardpenman/pywhois/pull/27).

Error handling remains unmodified though.
