### ISSUE TITLE
the sg domain not  Expiry Date

### ISSUE THREAD

**Issue by dcl-lily** [richardpenman/whois#222]
>>> a = whois.whois("abc.sg")
>>> a
{'domain_name': 'abc.sg', 'registrant_name': None, 'registrar': 'Key-Systems GmbH', 'creation_date': datetime.datetime(2022, 4, 3, 1, 47), 'expiration_date': None, 'dnssec': None}

**Comment by lelutin** [comment]
this is now being set on latest master commit and can be closed
