### ISSUE TITLE
Library returns multiple timestamps per field, have no idea what it means

### ISSUE THREAD

**Issue by digitalcortex** [richardpenman/whois#236]
I tried running whois query on PRIORITYTRUSTSERVICES.COM however the library returns the following timestamps:
```
"updated_date": [
    "2022-09-21 14:01:00",
    "2021-11-08 01:10:49"
  ],
  "creation_date": [
    "2012-12-05 20:39:17",
    "2012-12-05 15:39:17"
  ],
  "expiration_date": [
    "2024-12-05 20:39:17",
    "2024-12-05 15:39:17"
  ],
```

What does it mean? It seems that time stamps represent the time in different time zones but not clear which one is which.

Furthermore updated_date has multiple dates totally different from each other. Does the library show the entire history of updates for the domain?

**Comment by richardpenman** [comment]
The library scans the whois text and extracts all the updated / creation / expiration dates. So in this case multiple were found.

You can run whois `PRIORITYTRUSTSERVICES.COM` yourself to understand better what these dates indicate.
