### ISSUE TITLE
New Pypi release?

### ISSUE THREAD

**Issue by liquidsec** [richardpenman/whois#243]
Hey, just want to first say thanks for all your efforts on this library.

I use it extensively as an upstream dependency in my project [baddns](https://github.com/blacklanternsecurity/baddns)  Which, is it self a upstream dependency for BBOT [bbot](https://github.com/blacklanternsecurity/bbot/), a very large project I am also a contributor on.

I noticed you have been very active fixing a lot of issues lately. However, because of limitations with pip, I cannot make use of them. This is because if your project is a pip package, all of it its dependencies MUST also be pip packages. I cannot directly reference the git repo to pin a version, for example. 

So currently I have this issue:

![image](https://github.com/user-attachments/assets/3968391d-b081-4b1f-ba72-50c9acca76f9)

There isn't a good solution for silencing this error for me, and it also is bubbling up to BBOT:

https://github.com/blacklanternsecurity/bbot/issues/1673

However, I think you probably already fixed this, based on your test here:

https://github.com/richardpenman/whois/pull/209/files

So I guess I am just hoping you can do a pypi release soon, so we can take advantage of all the improvements you've made over the last months. Thanks!

**Comment by richardpenman** [comment]
sure have released a new version, sorry for delay
