### ISSUE TITLE
Whois for .ch domain is not working properly

### ISSUE THREAD

**Issue by carininet** [richardpenman/whois#246]
Since 1 January 2021, personal data associated with registered domain names is no longer disclosed in standard WHOIS queries. This limitation affects many WHOIS clients, including python-whois.

To address this, could you add support for retrieving domain data through RDAP queries? For instance, using an RDAP query (e.g. https://rdap.nic.ch/domain/carini.ch) could provide access to publicly available domain data like Registrar name, Registration date, Nameservers.

**Comment by richardpenman** [comment]
That's awesome. I would welcome a PR adding support for RDAP.

**Comment by carininet** [comment]
I have really no experience in contributing to Github project and a very little proficiency in Python, I can try to bring in contribution but I need some tutoring.

**Comment by richardpenman** [comment]
If you create an initial pull request I can give feedback how to improve it.

**Comment by pieterhartel** [comment]
Is there a list of top level domains that do not support the classical whois, i.e. RDAP only domains?

**Comment by carininet** [comment]
> Is there a list of top level domains that do not support the classical whois, i.e. RDAP only domains?

AFAIK, `.ch` (Switzerland) and `.li` (Liechtenstein) domains have required RDAP since January 1, 2021. Personal domain data is private by default, while non-personal data (registrar, name servers, and registration date) is only available through RDAP.

Registrar and DNS information are useful for a small utility I wrote ([dnscrawler](https://sourceforge.net/projects/dnscrawler/)), which extracts a CSV table from a list of domains.
