### ISSUE TITLE
No domain status for .ai domains

### ISSUE THREAD

**Issue by hedgieinsocks** [richardpenman/whois#256]
Hi, I've noticed there is a missing grep for domain status in .ai parser. I think it should be added somewhere [here](https://github.com/richardpenman/whois/blob/0248325caee193fbb7d3a6174ab7a64eea83ff69/whois/parser.py#L2078).

The raw output:

```
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
```

**Comment by richardpenman** [comment]
Great, send a PR and I'll merge
