### ISSUE TITLE
inconsistency across TLDs with domain_status vs status

### ISSUE THREAD

**Issue by lelutin** [richardpenman/whois#26]
Hi there,

thanks for this lib, parsing whois is quite the horrible task to achieve :(

I'm wondering why only a handful of TLDs are getting a `domain_status` field in their results while all others have a `status` field? This makes checking for this value inconsistent depending on the TLD being asked.

wouldn't it be better if TLDs that currently have a `domain_status` field get a one-item aray as a value for `status` instead?

**Comment by lelutin** [comment]
The same kind of inconsistency is also apparent with all `*_date` values : sometimes they're a `datetime.datetime` object while others they are a list of `datetime.datetime` objects.

it would be a lot better to always get a list even though there's only one item in it since it would make using results from the library a lot easier

**Comment by richardpenman** [comment]
definitely - patch welcome

**Comment by elguitar** [comment]
There's a separate issue for inconsistencies of `*_date` values in https://github.com/richardpenman/whois/issues/43.
