### ISSUE TITLE
Lack of consistency in WHOIS results

### ISSUE THREAD

**Issue by pnmartinez** [richardpenman/whois#42]
Issue description
===

Performing the same WHOIS can randomly return successful results or PyErrors ("no match") for the same domain.

Results
===
I've performed a consistency study over a problematic list of domains: 25 WHOIS runs for the same 23 domains. Results can be seen in the next [gspread sheet](https://docs.google.com/spreadsheets/d/1-ghB27Iza_ONyuLNcPHGRfH3Kg-ERdFc2p6q53mAVXk/edit?usp=sharing), or posted in the comments.

Code used
===

```
import whois
import csv

domains_to_check = ['campingfriends', 'Getawaytrips', 'bedtrip', 'Roadtrip', 'campingvacation', 'parkgroup', 'campingtrip', 'Destinationsvacation', 'everyoneland', 'groupfriends', 'camperspot', 'landvacation', 'landGetaway', 'tripsgroup', 'friendsspot', 'roadcamper', 'campingspot', 'rentingvan', 'bedvans', 'tentspot', 'tripDestinations', 'tripvan', 'caravanDestinations']

lookup = []
for word in domains_to_check:
    lookup.append([word]) # We prepare a list of lists: [[domain1, run1, run2, ...], ...]

n = 0
while n < 25: # 25 runs of the same WHOISs
    print(n) 
    i = 0
    for word in domains_to_check:      
        try:
            whois.whois(word + '.com') # Succesful WHOIS: the domain is not available
            w = 'not available'
        except:
            w = 'available' # Unsuccesful WHOIS, "No match" PyError: domain available
        lookup[i].append(w)        
        i += 1
    n += 1

 # Writing to CSV
for row in lookup:
    with open('looping_error_output.csv',"a") as file:
        writer = csv.writer(file)
        writer.writerow(row)
print(lookup)
```

**Comment by pnmartinez** [comment]
Results (pasted here for those that prefer not to open Google Sheets)
===

|  **Term (+.com)** | **Run 1** | **Run 2** | **Run 3** | **Run 4** | **Run 5** | **Run 6** | **Run 7** | **Run 8** | **Run 9** | **Run 10** | **Run 11** | **Run 12** | **Run 13** | **Run 14** | **Run 15** | **Run 16** | **Run 17** | **Run 18** | **Run 19** | **Run 20** | **Run 21** | **Run 22** | **Run 23** | **Run 24** | **Run 25** |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
|  campingfriends | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available |
|  Getawaytrips | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available |
|  bedtrip | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available |
|  Roadtrip | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available |
|  campingvacation | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available |
|  parkgroup | not available | not available | not available | *available* | *available* | not available | not available | not available | not available | not available | *available* | *available* | not available | not available | *available* | *available* | not available | not available | *available* | *available* | *available* | not available | *available* | *available* | not available |
|  campingtrip | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available |
|  Destinationsvacation | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available |
|  everyoneland | not available | not available | not available | not available | not available | not available | not available | not available | *available* | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available |
|  groupfriends | not available | not available | not available | not available | not available | not available | not available | not available | *available* | *available* | not available | not available | not available | not available | not available | *available* | not available | not available | not available | not available | not available | not available | not available | not available | not available |
|  camperspot | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available |
|  landvacation | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available |
|  landGetaway | not available | not available | not available | not available | not available | not available | not available | *available* | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available |
|  tripsgroup | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available |
|  friendsspot | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | *available* | not available | not available | not available | not available | not available | not available | not available |
|  roadcamper | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | *available* |
|  campingspot | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available |
|  rentingvan | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available |
|  bedvans | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available |
|  tentspot | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available |
|  tripDestinations | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available |
|  tripvan | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available |
|  caravanDestinations | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available | not available |

**Comment by richardpenman** [comment]
looks like network problem if results are inconsistent - perhaps IP is being blocked

**Comment by pnmartinez** [comment]
> looks like network problem if results are inconsistent - perhaps IP is being blocked

It would be nice if the package was able to log or print a warning in that case.

**Comment by richardpenman** [comment]
patch welcome
