### ISSUE TITLE
More granular exceptions

### ISSUE THREAD

**Issue by creffett** [richardpenman/whois#49]
It would be nice if the exceptions were more granular than the current PywhoisError - the code I'm working with would benefit from knowing more specifically what's gone wrong with a whois lookup. From looking at the code, I see three distinct classes of exception: TLD doesn't have a whois server (the exception in `class WhoisEntry`), invalid input (the exception in `def load` if we get "no whois server is known for this kind of object`), and domain couldn't be found in whois (the exception in the WhoisEntry subclasses). I'm thinking the best approach would be to have three subclasses of PywhoisError; that way, existing usage won't change behavior and it gives users an easy way to handle "I want to catch whois errors, I don't care what the meaning of the error is" cases but also lets people handle specific errors if they care. If this sounds like something you would like to add, let me know and I can prepare a patch.

**Comment by richardpenman** [comment]
sure that makes sense - patch very much welcome
