### ISSUE TITLE
whois.extract_domain doesn't handle second-level-only TLDs correctly

### ISSUE THREAD

**Issue by creffett** [richardpenman/whois#50]
If a domain doesn't have any top-level TLDs in the public suffix list (see, for example, the .za TLD - there is no .za, only .co.za, .ac.za, etc.), then whois.extract_domain returns an incorrect result. For example, `whois.extract_domain('google.co.za')` returns 'za' instead of 'google.co.za'. Patch coming shortly.

**Comment by richardpenman** [comment]
thanks - have merged PR
