### ISSUE TITLE
EU parser

### ISSUE THREAD

**Issue by esacco83** [richardpenman/whois#56]
I think the regex for extract the registrar in .eu domain is not correct.

`~$ whois -h whois.eu emanuelesacco.eu`

```
Domain: emanuelesacco.eu
Script: LATIN

Registrant:
        NOT DISCLOSED!
        Visit www.eurid.eu for webbased WHOIS.

Technical:
        Organisation: Register S.p.A.
        Language: it
        Email: support@register.it

Registrar:
        Name: Register S.p.A.
        Website: https://www.register.it/

Name servers:
        ns1.register.it
        ns2.register.it

Please visit www.eurid.eu for more info.
```

The actual regex is 
`        'registrar': r'Registrar: *Name: *([^\n\r]+)',`
but I think it would be 
`        'registrar': r'Registrar: *[\n\r]+\s*Name: *([^\n\r]+)',
`

**Comment by richardpenman** [comment]
these formats change over time - patches very welcome

**Comment by Crash-1** [comment]
Updated parser for EU TLD now it can get DNSSEC info for the domain and correctly return all other data #67

**Comment by JensTimmerman** [comment]
the registrant here is never disclosed, I noticed the eurid.eu page has an api to get the data via the web based whois. Is it within the scope of this project to talk to that api to get the correct data and return it? If so, I can work on a patch...

**Comment by richardpenman** [comment]
hmm I think that would be beyond the scope - this module is meant to be for wrapping whois servers rather than scraping API's
