### ISSUE TITLE
Issues with South African domains

### ISSUE THREAD

**Issue by mzpqnxow** [richardpenman/whois#57]
Hello- I recently started using your project to collect domain registrant information for a large number of domains spanning many countries. Among them are domains in South Africa. I am having problems with queries for them- the behavior I am getting is a failure to connect to what it thinks is the correct server for ZA domains. The connection times out. It's not an issue with a network block or rate limit as I've tried on a few different servers- it's simply receiving bad info back when it tries to find the correct whois server for .co.za it seems.

I haven't looked too much at the code (though I'm happy to) but I did take a look at what was going on with `tcpdump` and `strace` because the Debian whois client does OK with these domains. Here's what `python-whois` behavior looks like:

- When it starts up, the DNS query goes out for za.whois-servers.net
- This returns a CNAME to whois.nic.za, which resolves to 196.29.59.37
- The connection to the whois service @ 196.29.59.37 on TCP/43 then hangs until timing out- it never establishes a connection, it's just `SYN-SENT`

When I use the native `whois` client that comes with Debian 10, I see that it uses a DNS query to `whois.registry.net.za` to find `coza-whois.dns.net.za`, which it then successfully queries on TCP/43

I'm more familiar with RDAP than WHOIS so I don't know if you should be using a diffferent "bootstrap" DNS name (if that's the term here?) to find the South Africa whois service or what. I just know it is not working and that this is the behavior

Any thoughts on this? I haven't found issues with any other countries (yet) but if I do I will throw them into this issue if you're interesting in trying to address them. If you don't have the time but will take PRs I will try to make time to do it myself but I would like to hear what you have to say about it before spending any time on it

Thanks, great project, appreciate your work

EDIT: Example domain: bounceking.co.za

**Comment by richardpenman** [comment]
sorry not sure what is going on here - would definitely accept a PR to fix this

**Comment by mzpqnxow** [comment]
I'm putting a note here for later, I don't know why I didn't add this before- for (at least) south africa, it seems whois.registry.net.za should be used:

```
14:19:11 › whois --verbose bounceking.co.za    
Using server whois.registry.net.za.
Query string: "bounceking.co.za"

Domain Name: bounceking.co.za
Registry Domain ID: DOM_258OZ-CO.ZA
Registrar WHOIS Server: Whois.markmonitor.com
...
```

I'll come back with a PR, this can be left closed for now, thanks. I had completely forgotten about this until you closed it :)
