### ISSUE TITLE
Error trying to connect to socket: closing socket

### ISSUE THREAD

**Issue by zhangluya1987** [richardpenman/whois#58]
Hi,
I found the following error during use, Below is my debug information.
my VPS is in Los Angeles, USA.
"""
Error trying to connect to live.whois-servers.net socket: closing socket
Error trying to connect to space.whois-servers.net socket: closing socket
Error trying to connect to store.whois-servers.net socket: closing socket
Error trying to connect to vip.whois-servers.net socket: closing socket
Error trying to connect to website.whois-servers.net socket: closing socket
Error trying to connect to cn.whois-servers.net socket: closing socket
Error trying to connect to whois.aliyun.com socket: closing socket
"""

**Comment by richardpenman** [comment]
could you show the code used?
