### ISSUE TITLE
Some .io domains returns "Error trying to connect to socket: closing socket" but still works

### ISSUE THREAD

**Issue by jryberg** [richardpenman/whois#60]
Hi,

I'm evaluating this component and it does work but for every query to some specific .io domains returns "Error trying to connect to socket: closing socket" but it will still be able to get whois information.

The dns lookup for io returns whois.afilias.net and if I run whois.py -h whois.afilias.net <domain>.io then I got the result without any errors.

Note that google.io does not behave like this.

Are registrar used somehow and different domains behaves different?

I can provide domain name in PM if needed

Best regards Johan

**Comment by jryberg** [comment]
TCP communication looks different when using -h flag compared how to the imported function behaves when doing whois.whois(domain)

It seems it tries to connect to the registrar and in this case it's whois.marcaria.com that resolves to 45.60.33.228 

When trying to run python3 whois.py -h 45.60.33.228.43 google.io I got something familiar back
`Error trying to connect to socket: closing socket` 

I assume this component are trying to use registrar whois server as well? And in my case it's currently broken

**Comment by jryberg** [comment]
I received further information from Marcaria, they state they only offer whois via https and not port 43

Is there any way to fix this issue?

**Comment by mrjackson** [comment]
I'm seeing what I think is the same error with any domains that use whois.name.com
On 0.7.2 it wouldn't work at all and output nothing, after upgrading to 0.7.3 I get the correct output along with `Error trying to connect to socket: closing socket`

**Comment by gh0std3v** [comment]
I've been having this issue, but the whois request works for me. The main issue is using a `print()` to log the error to standard output. Maybe logging it to a file or throwing an exception for the user to handle would be better?

**Comment by Silverlink34** [comment]
I am getting the same problem - I am iterating over a list of a couple hundred domains to clean up name servers. The whois lookup results are working properly, but this error keeps popping up in my output. 

I am trying to use a progress bar in my command-line application but if anything is printed during the progressbar it makes the bar continue progressing on the next line.. and the error pops up so much that my whole command window is nearly filled with the progressbar. Need to be able to suppress the output of this error if possible.

**Comment by Silverlink34** [comment]
> I am getting the same problem - I am iterating over a list of a couple hundred domains to clean up name servers. The whois lookup results are working properly, but this error keeps popping up in my output.
> 
> I am trying to use a progress bar in my command-line application but if anything is printed during the progressbar it makes the bar continue progressing on the next line.. and the error pops up so much that my whole command window is nearly filled with the progressbar. Need to be able to suppress the output of this error if possible.

I was able to fix this issue by forcing the 'quick' flag like so: (also runs a LOT faster!!)
Note that according to the code, this skips checking for a regional whois server for local results. I'm only interested in checking if a domain has expired/isn't registered so I don't believe this will cause any issues with that sort of check.

`flags = 0`
`flags = flags | whois.NICClient.WHOIS_QUICK`
`w=whois.whois(domain, flags=flags)`

**Comment by LizardBlizzard** [comment]
Getting the same issue while querying **.com** domains. Not sure why this is happening but is there any reason to keep the direct print statement?
It's quite inconvenient, especially with async code where you have no clue which coroutine printed the message.

**Comment by Reikim** [comment]
+1 to this, the messages were really unnerving at first; I was really worried my requests were failing.

**Comment by kylejohnson** [comment]
I just submitted a PR to address this.

**Comment by Augustin-FL** [comment]
The PR of kylejohnson is nice, but it does not fix the actual issue ("``Error trying to connect to socket: closing socket`` being displayed to stdout")
I made a new PR ( #133 ) to complete kylejohnson's work
