### ISSUE TITLE
add support for many TLDs

### ISSUE THREAD

**Issue by ser-storchak** [richardpenman/whois#66]
no information about the date of domain registration:
md
to
at
jp
com.cy
lv
im
vn
goog
gov
de
co.il
рф

**Comment by richardpenman** [comment]
patch welcome!

**Comment by ser-storchak** [comment]
> 
> 
> patch welcome!

md - False (e.g. idc.md)
to - False (e.g. http://lurkmore.to/)
at - False (e.g. https://ad4m.at/)
jp - False (e.g.  https://adingo.jp/)
com.cy - False (e.g. https://alfacapital.com.cy/)
lv - False (e.g. http://eclub.lv/)
im - False (e.g. https://bash.im/)
vn  - False (e.g. https://zalo-api.zadn.vn/)
goog - False (e.g. https://rcs.telephony.goog/)
gov -  False (e.g. https://time.nist.gov/)
de -  False (e.g. https://www.computerbild.de/)
co.il -  False (e.g. https://www.orbita.co.il/)
рф - False (e.g. http://www.xn--80abukoph.xn--p1ai/)
