### ISSUE TITLE
Issue with .si domains

### ISSUE THREAD

**Issue by MilosMDodic** [richardpenman/whois#74]
I have issues with two .si domains (leanpay.si and kupinaobroke.si).

When trying to use python-whois via gcloud, I get "Error trying to connect to socket: closing socket", and all fields return as null ("expiration_date": null, etc).

Is there a workaround for this, or can this be added perhaps?

**Comment by fgeek** [comment]
Works for me. Are you using latest version? I tested with b5623ed25cfa58d9457d30dae640e69b9e530b23. Please note that there might have been temporary issues with WHOIS server also.
```
>>> w = whois.whois('leanpay.si')
>>> print(w)
{
  "domain_name": "leanpay.si",
  "registrar": "DHH.si d.o.o.",
  "name_servers": [
    "ns-cloud-c1.googledomains.com",
    "ns-cloud-c2.googledomains.com",
    "ns-cloud-c3.googledomains.com",
    "ns-cloud-c4.googledomains.com"
  ],
  "registrant_name": "G1000772",
  "creation_date": "2017-08-07 00:00:00",
  "expiration_date": "2021-08-07 00:00:00"
}
```
