### ISSUE TITLE
.nl domains show limited info

### ISSUE THREAD

**Issue by Kenan-Mu** [richardpenman/whois#81]
As the title says. The .nl domains show very limited to none information about the domain.
For example, my creation date returns empty or none values, but when it's used on .com (for example) it works completely fine.

**Comment by tlansec** [comment]
The author of the repository makes it clear in the README that you can submit a patch if you find particular TLD's are not supported. In this case you can add the following code to whois.py to get a reasonable response:

to the NICClient class:

```
NL_HOST = 'whois.domain-registry.nl'
```

to choose_server()

````
elif tld == 'nl':
            return NICClient.NL_HOST
```

Cheers,
Tom

**Comment by Kenan-Mu** [comment]
Thank you @tlansec. I have completely missed that point in the README, and got lost on the internet. I have successfully added you code, and have created a pull request.
