### ISSUE TITLE
import whois  will run test.py

### ISSUE THREAD

**Issue by 984958198** [richardpenman/whois#88]
The import whois will execute the test.py file under the current path. Is that a bit inappropriate?

**Comment by richardpenman** [comment]
could you clarify what you are referring to?

**Comment by 984958198** [comment]
![image](https://user-images.githubusercontent.com/9883283/128108250-117f2eea-de61-4681-9ba3-cfe664ae5125.png)

When my test.py has an exception, the project will not run.

The reason is that the source code will import test.py. I do not know the specific function of WHOis, so I ask whether it is reasonable to import test.py

**Comment by richardpenman** [comment]
That file is not part of this project.

If is dependency: 
https://github.com/PythonCharmers/python-future/blob/master/src/future/standard_library/__init__.py

**Comment by 984958198** [comment]
![image](https://user-images.githubusercontent.com/9883283/128277552-d3cc0b35-9c3a-44b3-851e-f5364fd9aa68.png)
The introduction of the project led to
