### ISSUE TITLE
Timeout not captured from code

### ISSUE THREAD

**Issue by erenturkm** [richardpenman/whois#94]
Hi,

While requesting whois information I get timeout from whois server as shown in response written to screen:
"Error trying to connect to socket: closing socket"

There is nothing returned as error (No Exception) and I get an empty construct. It gets tricky to check whether it was a network error (like here) or if server returned empty on certain fields. Ideally I would expect an exception just like if name is not found (which raises an exception.

**Comment by richardpenman** [comment]
yeah that's a good idea, but difficulty is each whois server handles this differently. Feel free to send a pull request if you have a solution.
