### ISSUE TITLE
whois closing socket error

### ISSUE THREAD

**Issue by hacktorious** [richardpenman/whois#99]
This basic example code doesn't work.  Any thoughts?

`import whois`

```
def seeAllWHOISdata():
    w = whois.whois('reddit.com')
    print(w)
```

`seeAllWHOISdata()`

```
Error trying to connect to socket: closing socket
{
  "domain_name": null,
  "registrar": null,
  "whois_server": null,
  "referral_url": null,
  "updated_date": null,
  "creation_date": null,
  "expiration_date": null,
  "name_servers": null,
  "status": null,
  "emails": null,
  "dnssec": null,
  "name": null,
  "org": null,
  "address": null,
  "city": null,
  "state": null,
  "zipcode": null,
  "country": null
}
```

**Comment by istiak101** [comment]
Possibly the IP is blacklisted/not allowed to query the registry database. Maybe try with another IP?

**Comment by joanyy** [comment]
did you solve it? the same problem with me

**Comment by hacktorious** [comment]
Sorry, yes, this is solved.

**Comment by judog01** [comment]
How did you solve the problem? I am still getting this error.

**Comment by freedom45678** [comment]
How did you solve the problem? I am still getting this error.

**Comment by ev01ing** [comment]
> How did you solve the problem? I am still getting this error.

> How did you solve the problem? I am still getting this error.

too manay request so the whois server banned your ip's request. you should use a proxy or request tomorow

**Comment by istiak101** [comment]
I wonder why people still use whois. There is much more modern and robust thing like RDAP. Easier to parse json response, standard data format, doesn't need an extra port to run, uses http/https, can filter out abuse more better...

**Comment by ev01ing** [comment]
> I wonder why people still use whois. There is much more modern and robust thing like RDAP. Easier to parse json response, standard data format, doesn't need an extra port to run, uses http/https, can filter out abuse more better...

becouse there are so manay people don't know RDAP.
I known RDAP just several days ago. But my whois spider run for almost five years.

RDAP need manay years to let poople know it and switch to use it.
